version: '3.8'

services:
  rabbitmq:
    image: cr.yandex/mirror/rabbitmq:3-management
    container_name: lab_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./api_service
    container_name: lab_api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build: ./worker_service
    depends_on:
      - rabbitmq